### ISSUE TITLE
OLD flag

### ISSUE THREAD

**Issue by acs-ferreira** [staxDB/announcements#27]
Shouldn't the `Old` flag be positioned at the same level then the `Announcement` badge?

See screenshot:
![image](https://user-images.githubusercontent.com/12234510/35804358-d05822e4-0a77-11e8-8b95-77b3260c94e0.png)

Like Calendar module:
![image](https://user-images.githubusercontent.com/12234510/35804546-8acfe076-0a78-11e8-9481-e64cdab87a0f.png)

This for UI/UX reasons.

**Comment by staxDB** [comment]
This would look a lot better! 
However, I am currently working on an extended task module and can't yet implement the changes.
I wanted to implement the module as an AddOn controller anyway, so that every post gets the "read" function.

**Comment by staxDB** [comment]
Added in 28ac2bb1e9e20fe325181cd83f698a7bf85121c8
