### ISSUE TITLE
Editing the post reset the statistics

### ISSUE THREAD

**Issue by funkycram** [staxDB/announcements#35]
If you edit the content of the post, the statistics get back to all "non read".

**Comment by staxDB** [comment]
That's the idea. If someone makes an announcement and revises it, everyone should receive the message again and the read statistics will be reset. Otherwise the users might be informed about an outdated status of the message, which should be avoided with this module.

**Comment by funkycram** [comment]
Thanks for your quick reply !
OK, I understand. So a feature request would be to have a checkbox "notify the change and reset statistics counter". Because sometimes the change is very small (spelling mistake, etc.)

**Comment by staxDB** [comment]
OK, that would certainly be a good option.If I find the time to realize it...

**Comment by funkycram** [comment]
Yes of course, it's already really great from you to have developed this module open source !!

**Comment by staxDB** [comment]
With the latest version you'll now have the option to configure the notifications-module under `admin->modules`
Here you can specify the notification-settings.

To test the latest features, just overwrite the old folder with the new one, there is no need to uninstall or disable the old version!
After overwriting the old version with the new one, please go to `admin->information->database` to let the migrations run.

After that, you can test the features. Please contact me, if something went wrong!

**Comment by funkycram** [comment]
Works like a charm !! Thanks a lot !
